# Extract Dataset

In [16]:
import numpy as np
import h5py
import os

f = h5py.File(r'../Data/GOLD_XYZ_OSC.0001_1024.hdf5','r')
dir_path = r'../ExtractDataset'
modu_snr_size = 1200
print(f['X'].shape)
print(f['Y'].shape)
print(f['Z'].shape)
print(f['Y'][100000])
print(f['Z'][100000])

(2555904, 1024, 2)
(2555904, 24)
(2555904, 1)
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[28]


In [10]:
for modu in range(24):
    X_list = []
    Y_list = []
    Z_list = []
    print('part ',modu)
    start_modu = modu*106496
    for snr in range(26):
        start_snr = start_modu + snr*4096
        idx_list = np.random.choice(range(0,4096),size=modu_snr_size,replace=False)
        print(idx_list)
        X = f['X'][start_snr:start_snr+4096][idx_list]
        #X = X[:,0:768,:]
        X_list.append(X)
        Y_list.append(f['Y'][start_snr:start_snr+4096][idx_list])
        Z_list.append(f['Z'][start_snr:start_snr+4096][idx_list])

    filename = dir_path + '/part' + str(modu) + '.h5'
    fw = h5py.File(filename,'w')
    fw['X'] = np.vstack(X_list)
    fw['Y'] = np.vstack(Y_list)
    fw['Z'] = np.vstack(Z_list)
    print('X shape:',fw['X'].shape)
    print('Y shape:',fw['Y'].shape)
    print('Z shape:',fw['Z'].shape)
    fw.close()
f.close()

part  0
[3844 2794 2073 ... 3658 1086  877]
[1215  342 2255 ... 2757 3927   32]
[2079 1879 1424 ... 1568 2390 4000]
[3194 3173  673 ... 2340 3805 2493]
[3167  607 2620 ... 1329  350 2613]
[3580 2985  147 ... 1782 3574 3818]
[1866 1271 1668 ...  332  724 2298]
[ 732 1874 1454 ... 3712 3895 3847]
[1314 3505 3367 ... 3683 2285 4077]
[ 579 2042 1445 ... 2072 2989  182]
[2557 3874 3198 ... 2049  919 3859]
[2408  832 3299 ... 1025 1903  989]
[2338 2402 3653 ...  111 3503 1955]
[2749 1138 4058 ...  866 1701 1748]
[1505 2957  536 ...  371 3631   45]
[1096 1254 1321 ...  203 1413 1248]
[2352 1884 3293 ... 3473 3801 3679]
[ 566 1277 1957 ...  925 1311  769]
[4021  728 3706 ... 2134  748  681]
[1227 1684  290 ...  429  219 3524]
[ 551 2633 3879 ... 3295 3231 3217]
[1844  138 4085 ... 1139  367 3593]
[1041 1109 1820 ... 2056  238 1682]
[ 882 3372 2114 ... 3098  883 1164]
[3430  292 3624 ... 2316  518 1794]
[ 441 2127 1638 ...  111  429 3358]
X shape: (31200, 1024, 2)
Y shape: (31200, 24)
Z shape: 

KeyboardInterrupt: 